### ISSUE TITLE
About Meを作る

### ISSUE THREAD

**Issue by TasukuNakano** [TasukuNakano/TasukuNakano.github.io#2]
#1 のうちのひとつ

今のところわかっているのは
```
menu:
  Home: /
  Archives: /archives
+  About Me: /about_me
```
を追加すると、リンクが増える。
ファイルをどう編集するかは調べ中
